version: 2

#executorType: docker
#containerInfo:
#  - image: circleci/android:api-27-alpha
#    cmd: ["/bin/bash"]
jobs:
  build:
    working_directory: ~/android-ponewheel
    docker:
      - image: circleci/android:api-28
    environment:
      - _JAVA_OPTIONS: "-Xmx1024m"
      - JVM_OPTS: -Xmx1024m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon --stacktrace -PdisablePreDex androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew --no-daemon --stacktrace --max-workers 1 -PdisablePreDex assemble check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results
